5554

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,7 +3,7 @@ name: Build and Deploy React Portfolio
 on:
   push:
     branches:
-      - terraform_azure_container_apps_02
+      - terraform_azure_container_apps_02_test
 
 permissions:
   contents: read
@@ -77,6 +77,14 @@ jobs:
             --resource-group $RESOURCE_GROUP \
             --location eastasia
 
+      - name: Check Container App Environment
+        run: |
+          echo "=== Container App Environment ==="
+          az containerapp env show \
+            --name $CONTAINER_APP_ENV \
+            --resource-group $RESOURCE_GROUP \
+            --output table || echo "Environment not found"
+
       - name: Check Container App
         run: |
           echo "=== Container App ==="
@@ -84,6 +92,42 @@ jobs:
             --name $CONTAINER_APP \
             --resource-group $RESOURCE_GROUP \
             --output table || echo "Container App not found"
+
+      - name: Ensure Container App Exists
+        run: |
+          if ! az containerapp show \
+            --name $CONTAINER_APP \
+            --resource-group $RESOURCE_GROUP >/dev/null 2>&1; then
+
+            echo "Creating Container App..."
+
+            az containerapp create \
+              --name $CONTAINER_APP \
+              --resource-group $RESOURCE_GROUP \
+              --environment $CONTAINER_APP_ENV \
+              --image $IMAGE_NAME \
+              --target-port 80 \
+              --ingress external \
+              --cpu 0.25 \
+              --memory 0.5Gi
+
+          else
+            echo "Updating Container App..."
+
+            az containerapp update \
+              --name $CONTAINER_APP \
+              --resource-group $RESOURCE_GROUP \
+              --image $IMAGE_NAME
+          fi
+
+      - name: Check Container App
+        run: |
+          echo "=== Container App ==="
+          az containerapp show \
+            --name $CONTAINER_APP \
+            --resource-group $RESOURCE_GROUP \
+            --output table || echo "Container App not found"
+
 
       # - name: Create Container App Environment
       #   run: |
@@ -128,3 +172,27 @@ jobs:
       #       --resource-group $RESOURCE_GROUP \
       #       --query properties.configuration.ingress.fqdn \
       #       -o tsv
+
+      - name: Wait 30 Minutes
+        run: sleep 1800
+
+      - name: Delete Container App
+        run: |
+          az containerapp delete \
+            --name portfolio-app \
+            --resource-group ReactStaticWebApp2026_group \
+            --yes
+
+      - name: Delete Container App Environment
+        run: |
+          az containerapp env delete \
+            --name portfolio-env \
+            --resource-group ReactStaticWebApp2026_group \
+            --yes
+
+      - name: Delete Log Analytics Workspace
+        run: |
+          az monitor log-analytics workspace delete \
+            --workspace-name workspace-eacttaticebpp2026groupOc9Y \
+            --resource-group ReactStaticWebApp2026_group \
+            --yes
