456

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,6 +12,7 @@ permissions:
 
 env:
   RESOURCE_GROUP: ReactStaticWebApp2026_group
+  WORKSPACE_NAME: myworkspace2026
   CONTAINER_APP: portfolio-app
   CONTAINER_APP_ENV: portfolio-env
   IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/reactmaster:latest
@@ -69,6 +70,21 @@ jobs:
           az group show --name "$RESOURCE_GROUP" --output table || echo "Resource Group not found"
 
 
+
+
+      # az monitor log-analytics workspace create \
+      #   --resource-group "$RESOURCE_GROUP" \
+      #   --workspace-name myworkspace
+
+      # az containerapp env create \
+      #   --name "$CONTAINER_APP_ENV" \
+      #   --resource-group "$RESOURCE_GROUP" \
+      #   --location eastasia \
+      #   --logs-workspace-id <workspace-id> \
+      #   --logs-workspace-key <workspace-key>
+
+
+
       # Step 2 :
       - name: Check or Create Container App Environment
         run: |
@@ -77,29 +93,72 @@ jobs:
             echo "Environment already exists"
           else
             echo "Creating Environment..."
-            az containerapp env create --name "$CONTAINER_APP_ENV" --resource-group "$RESOURCE_GROUP" --location eastasia
+            # az containerapp env create --name "$CONTAINER_APP_ENV" --resource-group "$RESOURCE_GROUP" --location eastasia
+
+            # Check or Create Log Analytics Workspace
+
+            
+
+            if az monitor log-analytics workspace show \
+              --resource-group "$RESOURCE_GROUP" \
+              --workspace-name "$WORKSPACE_NAME" >/dev/null 2>&1; then
+
+              echo "Log Analytics Workspace already exists"
+
+            else
+
+              echo "Creating Log Analytics Workspace..."
+
+              az monitor log-analytics workspace create \
+                --resource-group "$RESOURCE_GROUP" \
+                --workspace-name "$WORKSPACE_NAME"
+
+            fi
+
+            # Get Workspace ID
+
+            WORKSPACE_ID=$(az monitor log-analytics workspace show \
+              --resource-group "$RESOURCE_GROUP" \
+              --workspace-name "$WORKSPACE_NAME" \
+              --query customerId \
+              -o tsv)
+
+            # Get Workspace Key
+
+            WORKSPACE_KEY=$(az monitor log-analytics workspace get-shared-keys \
+              --resource-group "$RESOURCE_GROUP" \
+              --workspace-name "$WORKSPACE_NAME" \
+              --query primarySharedKey \
+              -o tsv)
+
+            echo "Workspace ID: $WORKSPACE_ID"
+
+            # Create Container App Environment
+
+            az containerapp env create \
+              --name "$CONTAINER_APP_ENV" \
+              --resource-group "$RESOURCE_GROUP" \
+              --location eastasia \
+              --logs-workspace-id "$WORKSPACE_ID" \
+              --logs-workspace-key "$WORKSPACE_KEY"
+
           fi
 
           echo "=== Container App Environment List ==="
           az containerapp env show --name "$CONTAINER_APP_ENV" --resource-group "$RESOURCE_GROUP" --output table || echo "Container App Environment not found"
 
+          echo "=== Container App Environment Log Analytics List ==="
+          az monitor log-analytics workspace list --output table
 
-      # Step 3 : Container App
-      # - name: Check Container App
+      # Step 3 : 
+      # - name: Create or Update Container App
       #   run: |
-      #     echo "=== Container App ==="
-      #     az containerapp show \
-      #       --name $CONTAINER_APP \
-      #       --resource-group $RESOURCE_GROUP \
-      #       --output table || echo "Container App not found"
-
-      # - name: Ensure Container App Exists
-      #   run: |
+      #     echo "=== 03: Container App Status ==="
       #     if ! az containerapp show \
       #       --name $CONTAINER_APP \
       #       --resource-group $RESOURCE_GROUP >/dev/null 2>&1; then
 
-      #       echo "Creating Container App..."
+      #       echo "Container App not found. Creating Container App..."
 
       #       az containerapp create \
       #         --name $CONTAINER_APP \
@@ -112,7 +171,7 @@ jobs:
       #         --memory 0.5Gi
 
       #     else
-      #       echo "Updating Container App..."
+      #       echo "Container App found. Updating Container App..."
 
       #       az containerapp update \
       #         --name $CONTAINER_APP \
@@ -120,6 +179,11 @@ jobs:
       #         --image $IMAGE_NAME
       #     fi
 
+      #     echo "=== Container App Details ==="
+      #     az containerapp show \
+      #       --name $CONTAINER_APP \
+      #       --resource-group $RESOURCE_GROUP \
+      #       --output table || echo "Container App not found"
 
       # Step 4:
       - name: List Resources in Resource Group
